Data - https://www.kaggle.com/competitions/fake-news/data?select=train.csv

In [13]:
import pandas as pd
df = pd.read_csv('train.csv', error_bad_lines=False, engine="python")
df

<ipython-input-13-b401a810e81c>:2: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv('train.csv', error_bad_lines=False, engine="python")
Skipping line 2394: unexpected end of data


id                                              title  \
0        0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1        1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2        2                  Why the Truth Might Get You Fired   
3        3  15 Civilians Killed In Single US Airstrike Hav...   
4        4  Iranian woman jailed for fictional unpublished...   
...    ...                                                ...   
2387  2387  Statue of Marx, Funded by China, Will Stand in...   
2388  2388  A Curious Plan to Fight Climate Change: Buy Mi...   
2389  2389  Study: Two Hours of Social Media Use a Day Dou...   
2390  2390  Skepticism and Support in South Korea as Ban K...   
2391  2391  Trump on ‘Women’s March’: ‘Why Didn’t These Pe...   

                                 author  \
0                         Darrell Lucus   
1                       Daniel J. Flynn   
2                    Consortiumnews.com   
3                       Jessica Purkiss   
4                        Howard Portnoy   
...                                 ...   
2387                       Melissa Eddy   
2388  Michael Corkery and Michael Wines   
2389                       Charlie Nash   
2390                      Choe Sang-Hun   
2391                    Dr. Susan Berry   

                                                   text  label  
0     House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1     Ever get the feeling your life circles the rou...      0  
2     Why the Truth Might Get You Fired October 29, ...      1  
3     Videos 15 Civilians Killed In Single US Airstr...      1  
4     Print \nAn Iranian woman has been sentenced to...      1  
...                                                 ...    ...  
2387  BERLIN  —   The bicentennial of the birth of K...      0  
2388  FAIRVIEW, W. Va.  —   The coal was piled about...      0  
2389  Just two hours of social media use a day can d...      0  
2390  HAENGCHI VILLAGE, South Korea  —   Each day hu...      0  
2391  President Donald Trump tweeted his response to...      0  

[2392 rows x 5 columns]

In [14]:
df = df.drop(columns = 'id', axis = 1)

In [15]:
df.head()

title              author  \
0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [16]:
# df = df.dropna()

In [17]:
## Independent ad dependent variable creation

X = df.drop(columns = 'label', axis =1)
y = df['label']

In [18]:
df.shape

(2392, 4)

In [19]:
X.shape

(2392, 3)

In [20]:
y.shape

(2392,)

In [23]:
df = df.dropna()

In [25]:
df.shape

(2084, 4)

In [26]:
## importing tensorflow
import tensorflow as tf
print(tf.__version__)

2.13.0


In [72]:
## Importing tensorflow packages

from tensorflow.keras.layers import Embedding, Dense, LSTM, Dropout
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [28]:
## vocabulary size

voc_size = 5000

## **Data cleaning**

In [46]:
messages = X.copy()
messages.head()

title              author  \
0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [48]:
messages.reset_index(inplace=True)
messages.head()

index                                              title  \
0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2                  Why the Truth Might Get You Fired   
3      3  15 Civilians Killed In Single US Airstrike Hav...   
4      4  Iranian woman jailed for fictional unpublished...   

               author                                               text  
0       Darrell Lucus  House Dem Aide: We Didn’t Even See Comey’s Let...  
1     Daniel J. Flynn  Ever get the feeling your life circles the rou...  
2  Consortiumnews.com  Why the Truth Might Get You Fired October 29, ...  
3     Jessica Purkiss  Videos 15 Civilians Killed In Single US Airstr...  
4      Howard Portnoy  Print \nAn Iranian woman has been sentenced to...

In [45]:
import nltk
import re
nltk.download('stopwords')
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [52]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []

for i in range(0,len(messages)):
  ## with the help of re(regular expression) library removing special characters
  ## apart from a-z and A-Z all the other alphabets or charters will be replaced by ' '
  review = re.sub('[^a-zA-Z]', ' ', str(messages['title'][i]))
  review = review.lower()
  review = review.split()
  ## applying stemming those words only which are not present in the english stopwords
  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [53]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'life life luxuri elton john favorit shark pictur stare long transcontinent flight',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'excerpt draft script donald trump q ampa black church pastor new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find hom

## **One Hot representation**

In [54]:
## Applying one_hot encoddinfg

oneHot_repr = [one_hot(words, voc_size) for words in corpus]
oneHot_repr

[[4833, 49, 1515, 945, 3945, 3281, 715, 1113, 4614, 2447],
 [505, 2612, 3536, 3102, 706, 3829, 356],
 [4620, 2202, 897, 2909],
 [4270, 2350, 1972, 4556, 2627, 3647],
 [942, 706, 4791, 421, 3001, 4833, 706, 3585, 1629, 485],
 [2303,
  4755,
  2643,
  2705,
  878,
  1609,
  541,
  2492,
  2616,
  4348,
  4951,
  577,
  2859,
  2758,
  356],
 [4263, 4263, 1300, 3101, 2523, 871, 2126, 94, 640, 3758, 4336, 3904],
 [213, 2199, 2026, 1688, 3871, 2790, 542, 3226, 4589, 1444, 170],
 [1585, 2289, 425, 2392, 1609, 4012, 2465, 1817, 1291, 3096, 4589, 1444, 170],
 [124, 1890, 4600, 1803, 3740, 1142, 1609, 4090, 4589, 1444, 170],
 [972, 1221, 2596, 209, 571, 781, 4451, 4288, 1609, 1704],
 [1756, 2317, 3429, 3595, 515, 4351, 1106, 214],
 [4436, 2689, 4793, 1070, 3105, 3026, 4224, 1988, 1507, 845, 2688],
 [4556, 1117, 3945, 781, 1609, 3740],
 [3011, 350, 920, 4447, 684, 3117, 3650, 4980, 2207],
 [1044, 536, 2467, 4848, 4358, 1754, 1574, 4589, 1444, 170],
 [932, 883, 1841, 2161, 1757, 4589, 1444, 170],

## **Applying Padding - creating embedded_docs**

In [58]:
## Applying padding for equalizing the number of words in a sentance
sent_length = 20
embedded_docs = pad_sequences(oneHot_repr, padding='pre', maxlen=sent_length)
# len(embedded_docs)
embedded_docs.shape

(2392, 20)

In [56]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 4833,
         49, 1515,  945, 3945, 3281,  715, 1113, 4614, 2447], dtype=int32)

## ***embedded_docs will be converted into final independent feature(X_final) while training the model

## **Model Creation**

In [115]:
embedding_vector_features = 40
model = Sequential()
#### Adding Embedding layer (i/p layer)------------
model.add(Embedding(voc_size, embedding_vector_features, input_length = sent_length))

#### Adding dropout layer for increasing accuracy and reducing overfitting
model.add(Dropout(0.3))

#### Adding LSTM layer - 1 layer with 100 neurons(hidden layer)----------------------
model.add(LSTM(200))

#### Adding dropout layer for increasing accuracy and reducing overfitting
model.add(Dropout(0.3))

#### Adding Dense layer (o/p layer)-----------
model.add(Dense(1, activation='sigmoid'))

#### Compiling the model----------------
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

print(model.summary())

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 20, 40)            200000    
                                                                 
 dropout_3 (Dropout)         (None, 20, 40)            0         
                                                                 
 lstm_4 (LSTM)               (None, 200)               192800    
                                                                 
 dropout_4 (Dropout)         (None, 200)               0         
                                                                 
 dense_3 (Dense)             (None, 1)                 201       
                                                                 
Total params: 393001 (1.50 MB)
Trainable params: 393001 (1.50 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


## **Final independent and dependent feature creation(X_final, y_final)**

In [116]:
import numpy as np
X_final = np.array(embedded_docs)
y_final = np.array(y)

In [117]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size = 0.33, random_state = 42)

## **Final Model Training**

In [118]:
### model is the sequential model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=64)

Epoch 1/10
26/26 [==============================] - 7s 176ms/step - loss: 0.6362 - accuracy: 0.6667 - val_loss: 0.5287 - val_accuracy: 0.7506
Epoch 2/10
26/26 [==============================] - 2s 78ms/step - loss: 0.4593 - accuracy: 0.8165 - val_loss: 0.4460 - val_accuracy: 0.7684
Epoch 3/10
26/26 [==============================] - 1s 46ms/step - loss: 0.2587 - accuracy: 0.9126 - val_loss: 0.3875 - val_accuracy: 0.8392
Epoch 4/10
26/26 [==============================] - 1s 52ms/step - loss: 0.1259 - accuracy: 0.9582 - val_loss: 0.3061 - val_accuracy: 0.8772
Epoch 5/10
26/26 [==============================] - 1s 35ms/step - loss: 0.0863 - accuracy: 0.9707 - val_loss: 0.2946 - val_accuracy: 0.8810
Epoch 6/10
26/26 [==============================] - 0s 19ms/step - loss: 0.0827 - accuracy: 0.9906 - val_loss: 0.3759 - val_accuracy: 0.8709
Epoch 7/10
26/26 [==============================] - 1s 47ms/step - loss: 0.0177 - accuracy: 0.9944 - val_loss: 0.4150 - val_accuracy: 0.8658
Epoch 8/10
2

## **Performance metrics and accuracy**







In [119]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

## As model.predict_classess has been depricated in tensorflow 2.6, and as it is a binary classificatin, we have used the below code
## For multi class classification --->  y_pred = np.argmax(model.predict(X_test), axis=-1)
y_pred = (model.predict(X_test) > 0.5).astype("int32")

25/25 [==============================] - 1s 3ms/step


In [120]:
y_pred

array([[1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
    

In [121]:
confusion_matrix(y_test, y_pred)

array([[325,  57],
       [ 46, 362]])

In [122]:
accuracy_score(y_pred, y_test)

0.8696202531645569

In [123]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.85      0.86       382
           1       0.86      0.89      0.88       408

    accuracy                           0.87       790
   macro avg       0.87      0.87      0.87       790
weighted avg       0.87      0.87      0.87       790

